### ISSUE TITLE
missing checks in _mkdir method in LocalFsClient

### ISSUE THREAD

**Issue by harsham4026** [airbnb/omniduct#71]
@matthewwardrop here in -mkdir method of LocalFsClient class we miss some of the checks. Will raise a PR for this issue. Please review and let me know if anything has to be changed

**Comment by harsham4026** [comment]
If the directory already exists, it makes sense to give some kind of warning that the directory already exists.

**Comment by matthewwardrop** [comment]
Hi @harsham4026 ! Thanks for getting involved!

It was actually an intentional decision (for better or worse) not to warn about this; since `mkdir` is used in contexts where all you care about is whether the directory exists, rather than whether it already exists when you ran `mkdir`. It definitely might make sense to flag this as an option, rather than the default behaviour, and is worthy of some thought :). I'll take a look at your PR (when it arrives), but the proper remedy may require more invasive changes to the API.

Thanks again @harsham4026 !

**Comment by harsham4026** [comment]
created PR for addressing this issue. Please have look into #72.

**Comment by harsham4026** [comment]
@matthewwardrop I had a question. Is there any work going on for supporting Azure Data Lake?

**Comment by naoyak** [comment]
@harsham4026 I don't think there is any Azure-related work at the moment. PRs welcome!

**Comment by harsham4026** [comment]
@naoyak implemented some changes in s3 in filesystems module. Please have a look into #73.

**Comment by matthewwardrop** [comment]
Closing this PR for ongoing discussion in #72.
